# Generated by Django 4.1.9 on 2023-05-08 13:11

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import utilities.json


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0092_delete_jobresult'),
        ('virtualization', '0034_standardize_description_comments'),
        ('vancis_plugin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMDBNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('cmdb_number', models.IntegerField()),
                ('comments', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='VirtualMachineData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('operating_system', models.CharField(max_length=50)),
                ('cmdb_number', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmdbnumber', to='vancis_plugin.cmdbnumber')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('virtual_machine', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='VirtualMachine', to='virtualization.virtualmachine')),
            ],
            options={
                'ordering': ('cmdb_number',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='accesslistrule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='accesslistrule',
            name='access_list',
        ),
        migrations.RemoveField(
            model_name='accesslistrule',
            name='destination_prefix',
        ),
        migrations.RemoveField(
            model_name='accesslistrule',
            name='source_prefix',
        ),
        migrations.RemoveField(
            model_name='accesslistrule',
            name='tags',
        ),
        migrations.DeleteModel(
            name='AccessList',
        ),
        migrations.DeleteModel(
            name='AccessListRule',
        ),
    ]
