# Generated by Django 4.1.9 on 2023-05-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vancis_plugin', '0002_cmdbnumber_virtualmachinedata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdbnumber',
            name='cmdb_number',
            field=models.IntegerField(unique=True),
        ),
    ]
