# Generated by Django 4.1.9 on 2023-05-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0034_standardize_description_comments'),
        ('vancis_plugin', '0004_alter_cmdbnumber_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualmachinedata',
            name='operating_system',
        ),
        migrations.AddField(
            model_name='virtualmachinedata',
            name='DBMS',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualmachinedata',
            name='Hypervisor_Agent',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualmachinedata',
            name='Hypervisor_HW_version',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualmachinedata',
            name='Hypervisor_UUID',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualmachinedata',
            name='LAPS',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualmachinedata',
            name='ManagedBy',
            field=models.CharField(default='Vancis', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualmachinedata',
            name='OTAP',
            field=models.CharField(default='ONT', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualmachinedata',
            name='SLA',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualmachinedata',
            name='SOCSIEM',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualmachinedata',
            name='Vulnerability_Scan',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualmachinedata',
            name='backup_job',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualmachinedata',
            name='backup_method',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualmachinedata',
            name='dependency_VM',
            field=models.ManyToManyField(null=True, to='virtualization.virtualmachine'),
        ),
        migrations.AddField(
            model_name='virtualmachinedata',
            name='documentation',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualmachinedata',
            name='domain',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualmachinedata',
            name='install_date',
            field=models.DateField(default='1970-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualmachinedata',
            name='managedAPP',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualmachinedata',
            name='managedDB',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualmachinedata',
            name='managedOS',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualmachinedata',
            name='monitoring',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualmachinedata',
            name='passwordmanager',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualmachinedata',
            name='ticket',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualmachinedata',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
