# Generated by Django 4.1.9 on 2023-05-24 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vancis_plugin', '0005_remove_virtualmachinedata_operating_system_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkdevicedata',
            name='operating_system',
        ),
        migrations.RemoveField(
            model_name='virtualmachinedata',
            name='DBMS',
        ),
        migrations.RemoveField(
            model_name='virtualmachinedata',
            name='Hypervisor_Agent',
        ),
        migrations.RemoveField(
            model_name='virtualmachinedata',
            name='Hypervisor_HW_version',
        ),
        migrations.RemoveField(
            model_name='virtualmachinedata',
            name='Hypervisor_UUID',
        ),
        migrations.RemoveField(
            model_name='virtualmachinedata',
            name='LAPS',
        ),
        migrations.RemoveField(
            model_name='virtualmachinedata',
            name='ManagedBy',
        ),
        migrations.RemoveField(
            model_name='virtualmachinedata',
            name='OTAP',
        ),
        migrations.RemoveField(
            model_name='virtualmachinedata',
            name='SLA',
        ),
        migrations.RemoveField(
            model_name='virtualmachinedata',
            name='SOCSIEM',
        ),
        migrations.RemoveField(
            model_name='virtualmachinedata',
            name='Vulnerability_Scan',
        ),
        migrations.RemoveField(
            model_name='virtualmachinedata',
            name='backup_job',
        ),
        migrations.RemoveField(
            model_name='virtualmachinedata',
            name='backup_method',
        ),
        migrations.RemoveField(
            model_name='virtualmachinedata',
            name='dependency_VM',
        ),
        migrations.RemoveField(
            model_name='virtualmachinedata',
            name='documentation',
        ),
        migrations.RemoveField(
            model_name='virtualmachinedata',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='virtualmachinedata',
            name='install_date',
        ),
        migrations.RemoveField(
            model_name='virtualmachinedata',
            name='managedAPP',
        ),
        migrations.RemoveField(
            model_name='virtualmachinedata',
            name='managedDB',
        ),
        migrations.RemoveField(
            model_name='virtualmachinedata',
            name='managedOS',
        ),
        migrations.RemoveField(
            model_name='virtualmachinedata',
            name='monitoring',
        ),
        migrations.RemoveField(
            model_name='virtualmachinedata',
            name='passwordmanager',
        ),
        migrations.RemoveField(
            model_name='virtualmachinedata',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='virtualmachinedata',
            name='url',
        ),
    ]
