# Generated by Django 4.1.9 on 2023-07-05 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0010_tenant_relax_uniqueness'),
        ('vancis_plugin', '0009_storagecluster_storagevolume'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagevolume',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant'),
            preserve_default=False,
        ),
    ]
