# Generated by Django 4.1.9 on 2023-07-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vancis_plugin', '0010_storagevolume_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagecluster',
            name='totalSize',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
