# Generated by Django 4.1.9 on 2023-07-06 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vancis_plugin', '0011_storagecluster_totalsize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storagevolume',
            old_name='totalSize',
            new_name='volSize',
        ),
    ]
