# Generated by Django 4.1.9 on 2023-07-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vancis_plugin', '0012_rename_totalsize_storagevolume_volsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagecluster',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='storagevolume',
            name='volName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
