# Generated by Django 4.1.9 on 2023-07-06 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vancis_plugin', '0013_alter_storagecluster_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagevolume',
            name='storageCluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storageVolumes', to='vancis_plugin.storagecluster'),
        ),
    ]
