# Generated by Django 4.2.8 on 2024-01-22 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vancis_plugin', '0014_alter_storagevolume_storagecluster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softwarepackage',
            old_name='klant',
            new_name='tenant',
        ),
    ]
